Add enum option to properties
WebThingsIO/virtual-things-adapter pull request #60
Opened 2021-04-22 13:06 UTC by bewee

This proposes adding an enum option for string properties, similar as min/max/multipleOf exist for numbers/integers.

I added this option as a string type, where one has to enter a valid JSON array (if no valid JSON is entered, not enum will be added to the property). I thought this may be helpful since one can just copy and paste the array from somewhere. But I think it may be more user-friendly to change the type to array of string?

2021-04-29 19:14 UTC, tim-hellhake commented on manifest.json
> +                    },
I'm curious, why not using an array?

```suggestion
                    "enum": {
                      "description": "Property values must be one of these options, given as a JSON Array. Only relevant for string properties.",
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
```

2021-04-29 22:13 UTC, bewee commented on manifest.json
> +                    },
> I added this option as a string type, where one has to enter a valid JSON array (if no valid JSON is entered, not enum will be added to the property). I thought this may be helpful since one can just copy and paste the array from somewhere. But I think it may be more user-friendly to change the type to array of string?

:D

2021-05-01 21:52 UTC, tim-hellhake requested changes

2021-05-01 21:52 UTC, tim-hellhake commented on virtual-things-adapter.js
> +              property.enum = JSON.parse(property.enum);
You don't need to parse it anymore :smile:

2021-05-01 22:34 UTC, bewee commented on virtual-things-adapter.js
> +              property.enum = JSON.parse(property.enum);
Good point😅

2021-05-05 22:45 UTC, tim-hellhake commented
The linter is unhappy :grimacing:

2021-05-06 07:52 UTC, bewee commented
I really have to get this VS Code extension running again on my computer😬😅

2021-05-06 22:09 UTC, merged